// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/airlines" | "/admin/airports" | "/admin/fleet" | "/admin/pilots" | "/admin/pireps" | "/admin/routes" | "/airline" | "/airline/airports" | "/airline/api-keys" | "/airline/awards" | "/airline/billing" | "/airline/dashboard" | "/airline/discord-notifications" | "/airline/event" | "/airline/feed" | "/airline/feed/[id]" | "/airline/fleet" | "/airline/flights" | "/airline/general" | "/airline/info" | "/airline/pilots" | "/airline/schedules" | "/airlines" | "/apply" | "/booking/[id]" | "/dashboard" | "/dashboard/airlines" | "/dashboard/airports/[icao]" | "/dashboard/book" | "/dashboard/booking/[id]" | "/dashboard/dispatch/[id]" | "/dashboard/events" | "/dashboard/leaderboard" | "/dashboard/pilots" | "/dashboard/pireps" | "/dashboard/pireps/submit" | "/dashboard/routes/[id]" | "/dashboard/settings" | "/dashboard/stats" | "/dashboard/tracking" | "/dispatch/[id]" | "/join" | "/login" | "/routes/[id]"
type AppRouteHandlerRoutes = "/api/acars/dispatch" | "/api/acars/session/end" | "/api/acars/session/heartbeat" | "/api/acars/session/start" | "/api/acars/sessions/active" | "/api/admin/airlines" | "/api/admin/airlines/[id]" | "/api/admin/airports" | "/api/admin/airports/[id]" | "/api/admin/fleet" | "/api/admin/pilots" | "/api/admin/pilots/[id]" | "/api/admin/pireps" | "/api/admin/pireps/[id]" | "/api/admin/routes" | "/api/admin/routes/[id]" | "/api/airline/airports" | "/api/airline/airports/[id]" | "/api/airline/api-keys" | "/api/airline/apply" | "/api/airline/awards" | "/api/airline/billing" | "/api/airline/discord" | "/api/airline/discord/test" | "/api/airline/events" | "/api/airline/events/[id]" | "/api/airline/fleet" | "/api/airline/info" | "/api/airline/me" | "/api/airline/notams" | "/api/airline/pilots" | "/api/airline/pilots/remove" | "/api/airline/pilots/suspend" | "/api/airline/pilots/unsuspend" | "/api/airline/posts" | "/api/airline/schedules" | "/api/airline/schedules/[id]" | "/api/airline/transfer-ownership" | "/api/airlines" | "/api/auth/[...nextauth]" | "/api/auth/register" | "/api/bookings" | "/api/bookings/[id]" | "/api/flyme/auth" | "/api/flyme/dispatches" | "/api/pilot/airline" | "/api/pilot/airline/select" | "/api/pilot/me" | "/api/pilot/profile" | "/api/pireps" | "/api/routes" | "/api/routes/[id]" | "/api/simbrief" | "/api/simbrief/getcode" | "/api/simbrief/ofp" | "/api/simbrief/submit" | "/api/stripe/create-checkout-session" | "/api/stripe/webhook" | "/api/support/report" | "/api/tracking/aircraft-photo" | "/api/tracking/airports" | "/api/tracking/live" | "/api/weather/metar"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/airline" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/airlines": {}
  "/admin/airports": {}
  "/admin/fleet": {}
  "/admin/pilots": {}
  "/admin/pireps": {}
  "/admin/routes": {}
  "/airline": {}
  "/airline/airports": {}
  "/airline/api-keys": {}
  "/airline/awards": {}
  "/airline/billing": {}
  "/airline/dashboard": {}
  "/airline/discord-notifications": {}
  "/airline/event": {}
  "/airline/feed": {}
  "/airline/feed/[id]": { "id": string; }
  "/airline/fleet": {}
  "/airline/flights": {}
  "/airline/general": {}
  "/airline/info": {}
  "/airline/pilots": {}
  "/airline/schedules": {}
  "/airlines": {}
  "/api/acars/dispatch": {}
  "/api/acars/session/end": {}
  "/api/acars/session/heartbeat": {}
  "/api/acars/session/start": {}
  "/api/acars/sessions/active": {}
  "/api/admin/airlines": {}
  "/api/admin/airlines/[id]": { "id": string; }
  "/api/admin/airports": {}
  "/api/admin/airports/[id]": { "id": string; }
  "/api/admin/fleet": {}
  "/api/admin/pilots": {}
  "/api/admin/pilots/[id]": { "id": string; }
  "/api/admin/pireps": {}
  "/api/admin/pireps/[id]": { "id": string; }
  "/api/admin/routes": {}
  "/api/admin/routes/[id]": { "id": string; }
  "/api/airline/airports": {}
  "/api/airline/airports/[id]": { "id": string; }
  "/api/airline/api-keys": {}
  "/api/airline/apply": {}
  "/api/airline/awards": {}
  "/api/airline/billing": {}
  "/api/airline/discord": {}
  "/api/airline/discord/test": {}
  "/api/airline/events": {}
  "/api/airline/events/[id]": { "id": string; }
  "/api/airline/fleet": {}
  "/api/airline/info": {}
  "/api/airline/me": {}
  "/api/airline/notams": {}
  "/api/airline/pilots": {}
  "/api/airline/pilots/remove": {}
  "/api/airline/pilots/suspend": {}
  "/api/airline/pilots/unsuspend": {}
  "/api/airline/posts": {}
  "/api/airline/schedules": {}
  "/api/airline/schedules/[id]": { "id": string; }
  "/api/airline/transfer-ownership": {}
  "/api/airlines": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/register": {}
  "/api/bookings": {}
  "/api/bookings/[id]": { "id": string; }
  "/api/flyme/auth": {}
  "/api/flyme/dispatches": {}
  "/api/pilot/airline": {}
  "/api/pilot/airline/select": {}
  "/api/pilot/me": {}
  "/api/pilot/profile": {}
  "/api/pireps": {}
  "/api/routes": {}
  "/api/routes/[id]": { "id": string; }
  "/api/simbrief": {}
  "/api/simbrief/getcode": {}
  "/api/simbrief/ofp": {}
  "/api/simbrief/submit": {}
  "/api/stripe/create-checkout-session": {}
  "/api/stripe/webhook": {}
  "/api/support/report": {}
  "/api/tracking/aircraft-photo": {}
  "/api/tracking/airports": {}
  "/api/tracking/live": {}
  "/api/weather/metar": {}
  "/apply": {}
  "/booking/[id]": { "id": string; }
  "/dashboard": {}
  "/dashboard/airlines": {}
  "/dashboard/airports/[icao]": { "icao": string; }
  "/dashboard/book": {}
  "/dashboard/booking/[id]": { "id": string; }
  "/dashboard/dispatch/[id]": { "id": string; }
  "/dashboard/events": {}
  "/dashboard/leaderboard": {}
  "/dashboard/pilots": {}
  "/dashboard/pireps": {}
  "/dashboard/pireps/submit": {}
  "/dashboard/routes/[id]": { "id": string; }
  "/dashboard/settings": {}
  "/dashboard/stats": {}
  "/dashboard/tracking": {}
  "/dispatch/[id]": { "id": string; }
  "/join": {}
  "/login": {}
  "/routes/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/airline": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
