// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/airlines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/airlines">> = Specific
  const handler = {} as typeof import("../../src/app/admin/airlines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/airports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/airports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/airports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/fleet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/fleet">> = Specific
  const handler = {} as typeof import("../../src/app/admin/fleet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pilots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pilots">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pilots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pireps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pireps">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pireps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/routes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/routes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/routes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/airports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/airports">> = Specific
  const handler = {} as typeof import("../../src/app/airline/airports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/airline/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/awards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/awards">> = Specific
  const handler = {} as typeof import("../../src/app/airline/awards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/billing">> = Specific
  const handler = {} as typeof import("../../src/app/airline/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/airline/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/discord-notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/discord-notifications">> = Specific
  const handler = {} as typeof import("../../src/app/airline/discord-notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/event/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/event">> = Specific
  const handler = {} as typeof import("../../src/app/airline/event/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/feed/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/feed/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/airline/feed/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/feed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/feed">> = Specific
  const handler = {} as typeof import("../../src/app/airline/feed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/fleet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/fleet">> = Specific
  const handler = {} as typeof import("../../src/app/airline/fleet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/flights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/flights">> = Specific
  const handler = {} as typeof import("../../src/app/airline/flights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/general">> = Specific
  const handler = {} as typeof import("../../src/app/airline/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/info/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/info">> = Specific
  const handler = {} as typeof import("../../src/app/airline/info/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline">> = Specific
  const handler = {} as typeof import("../../src/app/airline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/pilots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/pilots">> = Specific
  const handler = {} as typeof import("../../src/app/airline/pilots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/schedules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airline/schedules">> = Specific
  const handler = {} as typeof import("../../src/app/airline/schedules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airlines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/airlines">> = Specific
  const handler = {} as typeof import("../../src/app/airlines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apply">> = Specific
  const handler = {} as typeof import("../../src/app/apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/booking/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/booking/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/booking/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/airlines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/airlines">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/airlines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/airports/[icao]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/airports/[icao]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/airports/[icao]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/book">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/booking/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/booking/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/booking/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/dispatch/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/dispatch/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/dispatch/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/events">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/pilots/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pilots">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/pilots/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/pireps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pireps">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/pireps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/pireps/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pireps/submit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/pireps/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/routes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/routes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/routes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/stats">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tracking">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dispatch/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispatch/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dispatch/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/join/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/join">> = Specific
  const handler = {} as typeof import("../../src/app/join/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/routes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/routes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/routes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/acars/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/acars/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/api/acars/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/acars/session/end/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/acars/session/end">> = Specific
  const handler = {} as typeof import("../../src/app/api/acars/session/end/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/acars/session/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/acars/session/heartbeat">> = Specific
  const handler = {} as typeof import("../../src/app/api/acars/session/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/acars/session/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/acars/session/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/acars/session/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/acars/sessions/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/acars/sessions/active">> = Specific
  const handler = {} as typeof import("../../src/app/api/acars/sessions/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/airlines/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/airlines/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/airlines/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/airlines/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/airlines">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/airlines/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/airports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/airports/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/airports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/airports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/airports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/airports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/fleet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/fleet">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/fleet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pilots/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pilots/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pilots/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pilots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pilots">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pilots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pireps/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pireps/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pireps/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/pireps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pireps">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/pireps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/routes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/routes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/routes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/routes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/routes">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/routes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/airports/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/airports/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/airports/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/airports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/airports">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/airports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/apply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/apply">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/apply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/awards/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/awards">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/awards/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/billing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/billing">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/billing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/discord/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/discord">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/discord/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/discord/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/discord/test">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/discord/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/events/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/events/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/events/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/fleet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/fleet">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/fleet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/info">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/notams/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/notams">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/notams/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/pilots/remove/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/pilots/remove">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/pilots/remove/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/pilots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/pilots">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/pilots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/pilots/suspend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/pilots/suspend">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/pilots/suspend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/pilots/unsuspend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/pilots/unsuspend">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/pilots/unsuspend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/schedules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/schedules/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/schedules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/schedules">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airline/transfer-ownership/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airline/transfer-ownership">> = Specific
  const handler = {} as typeof import("../../src/app/api/airline/transfer-ownership/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/airlines/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/airlines">> = Specific
  const handler = {} as typeof import("../../src/app/api/airlines/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flyme/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flyme/auth">> = Specific
  const handler = {} as typeof import("../../src/app/api/flyme/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/flyme/dispatches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flyme/dispatches">> = Specific
  const handler = {} as typeof import("../../src/app/api/flyme/dispatches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pilot/airline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pilot/airline">> = Specific
  const handler = {} as typeof import("../../src/app/api/pilot/airline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pilot/airline/select/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pilot/airline/select">> = Specific
  const handler = {} as typeof import("../../src/app/api/pilot/airline/select/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pilot/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pilot/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/pilot/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pilot/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pilot/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/pilot/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pireps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pireps">> = Specific
  const handler = {} as typeof import("../../src/app/api/pireps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/routes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/routes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/routes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routes">> = Specific
  const handler = {} as typeof import("../../src/app/api/routes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/simbrief/getcode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simbrief/getcode">> = Specific
  const handler = {} as typeof import("../../src/app/api/simbrief/getcode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/simbrief/ofp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simbrief/ofp">> = Specific
  const handler = {} as typeof import("../../src/app/api/simbrief/ofp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/simbrief/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simbrief">> = Specific
  const handler = {} as typeof import("../../src/app/api/simbrief/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/simbrief/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simbrief/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/simbrief/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/create-checkout-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/create-checkout-session">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/create-checkout-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/support/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/support/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/support/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tracking/aircraft-photo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracking/aircraft-photo">> = Specific
  const handler = {} as typeof import("../../src/app/api/tracking/aircraft-photo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tracking/airports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracking/airports">> = Specific
  const handler = {} as typeof import("../../src/app/api/tracking/airports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tracking/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracking/live">> = Specific
  const handler = {} as typeof import("../../src/app/api/tracking/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/weather/metar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather/metar">> = Specific
  const handler = {} as typeof import("../../src/app/api/weather/metar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/airline/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/airline">> = Specific
  const handler = {} as typeof import("../../src/app/airline/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
