var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/bookings/route.js")
R.c("server/chunks/node_modules_next_8c7c2757._.js")
R.c("server/chunks/node_modules_next-auth_1810886e._.js")
R.c("server/chunks/node_modules_openid-client_d15f72b3._.js")
R.c("server/chunks/node_modules_5929141f._.js")
R.c("server/chunks/node_modules_c697dc78._.js")
R.c("server/chunks/[root-of-the-server]__d013ae2f._.js")
R.m("[project]/.next-internal/server/app/api/bookings/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/bookings/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/bookings/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
