export const PHASE2_DISCORD_EVENT_KEYS = [
  'PILOT_SIGNUP',
  'AIRLINE_APPLICATION_SUBMITTED',
  'PIREP_ACCEPTED',
  'SUPPORT_REPORT_SUBMITTED',
  'EVENT_PUBLISHED',
  'NOTAM_PUBLISHED',
  'FLIGHT_PLAN_FILED',
  'RADAR_STARTED',
  'RADAR_ENDED',
] as const

export type Phase2DiscordEventKey = (typeof PHASE2_DISCORD_EVENT_KEYS)[number]

export const AIRLINE_DISCORD_EVENT_KEYS = [
  'PILOT_SIGNUP',
  'PIREP_ACCEPTED',
  'EVENT_PUBLISHED',
  'NOTAM_PUBLISHED',
  'FLIGHT_PLAN_FILED',
  'RADAR_STARTED',
  'RADAR_ENDED',
] as const

export type AirlineDiscordEventKey = (typeof AIRLINE_DISCORD_EVENT_KEYS)[number]

export const PHASE2_DISCORD_EVENT_LABELS: Record<Phase2DiscordEventKey, string> = {
  PILOT_SIGNUP: 'New Pilot Signup',
  AIRLINE_APPLICATION_SUBMITTED: 'Airline Application Submitted',
  PIREP_ACCEPTED: 'Accepted Flight Log (PIREP)',
  SUPPORT_REPORT_SUBMITTED: 'Support Report (Issue/Question)',
  EVENT_PUBLISHED: 'Event Published',
  NOTAM_PUBLISHED: 'NOTAM Published',
  FLIGHT_PLAN_FILED: 'Flight Plan Filed (SimBrief)',
  RADAR_STARTED: 'Radar Session Started',
  RADAR_ENDED: 'Radar Session Ended',
}

export const AIRLINE_DISCORD_EVENT_LABELS: Record<AirlineDiscordEventKey, string> = {
  PILOT_SIGNUP: PHASE2_DISCORD_EVENT_LABELS.PILOT_SIGNUP,
  PIREP_ACCEPTED: PHASE2_DISCORD_EVENT_LABELS.PIREP_ACCEPTED,
  EVENT_PUBLISHED: PHASE2_DISCORD_EVENT_LABELS.EVENT_PUBLISHED,
  NOTAM_PUBLISHED: PHASE2_DISCORD_EVENT_LABELS.NOTAM_PUBLISHED,
  FLIGHT_PLAN_FILED: PHASE2_DISCORD_EVENT_LABELS.FLIGHT_PLAN_FILED,
  RADAR_STARTED: PHASE2_DISCORD_EVENT_LABELS.RADAR_STARTED,
  RADAR_ENDED: PHASE2_DISCORD_EVENT_LABELS.RADAR_ENDED,
}
